# -*- coding: utf-8 -*-
"""
Created on Sun Mar 31 10:40:26 2019

@author: Mohit
"""
# CORRELATION

# STEPS 
1.UNDERSTAND DATA = DISCRIPTIVE STATISTICS
                    NUMERIC
                    CHARACTER - FREQ/PERCENTAGE (NUMBER OF UNIQUE VALUE)
                    IDENTIFICATON COLUMNS - NUMERIC/CHARACTER (IF ALL VALUES ARE UNIWUE IN COLUMN)
                                            THIS IS NOT USED IN ANY ANALYSIS(WE CAN DROP THIS COLUMN OR SEPRATE THIS COLUMN)
                    
2.FINDING RELATION - TABLE(DATASET)
                     INDEX/ROWS(OBSERVATION)
                     COLUMN(VARIABLES)
                     

 
# =============================================================================
# VARIABLE 1 IS NUMERIC
# VARIABLE 2 IS NUMERIC
# METHOD - CORREALTION
# 
# VARIABLE 1 IS CHARACTER
# VARIABLE 2 IS CHARACTER
# METHOD - CHI SQUARE
# 
# VARIABLE 1 IS NUMERIC
# VARIABLE 2 IS CHARACTER(WITH UNIQUE VALUE)
# METHOD - T.TEST
# 
# VARIABLE 1 IS NUMERIC
# VARIABLE 2 IS CHARACTER(WITH MORE THEN 1 UNIQUE VALUE)
# METHOD - ANOVA
# =============================================================================

CORRELATION - IS USED TO MEASURE REALTIONSHIP BETWEEN TWO NUMBERIC VALUES

CORRELATION IS MEASURE BY CORREALTION COIFFECIANT(r)

r(xy)(CORRELATION B/W X&Y) = COR(XY)/(S(X)) X (S(Y))
                                CORRELATION OF X & Y/STD OF X & STD OF Y
                                
                                
- VALUE OF R LIES B/W -1 TO 1

-VE VALUE - NEGITIVE CORRELATION (BOTH VARIABLE MOVES IN OPPOSITE DIRECATION)
+VE VALUE - POSITIVE CORRELATION (BOTH VARIABLE MOVES IN SAME DIRECATION)

NO CORRELARTION - HORIZENTAL OR VERTICLE STRAIGHT LINE

|r| - 0 - 0.3 - WEAK CORRELATION
      0.3-0.5 - MODERATE CORRELATRION
      0.5-1.0 - STRONG CORRELATION
      
      
FUNCTIONS TO PERFORM CORRELATION
1. NUMPY - WORKS WITH INDIVIDUAL DATA
2. SCIPY - WORKS WITH INDIVIDUAL DATA
3. PANDAS - WORKS WITH DATAFRAME











